// 静态关卡内容（MVP 阶段硬编码；W2.3 改为从 SQLite 读）

use crate::types::*;

pub fn builtin_levels() -> Vec<Level> {
    vec![
        Level {
            id: "L1".to_string(),
            order_num: 1,
            title: "我的第一个 AI 视频".to_string(),
            description: "一句话生成 5 秒视频，认识 AI 视频创作".to_string(),
            cover_emoji: "🎬".to_string(),
            estimated_minutes: 20,
            reward_tokens: 30,
            difficulty: 1,
            prerequisites: vec![],
            video_subtitle: Some("让 AI 帮我们做一件从来没做过的事".to_string()),
            steps: vec![
                LevelStep {
                    id: "L1-s1".to_string(),
                    order_num: 1,
                    title: "看一段示例".to_string(),
                    instruction: "看一段 AI 生成的 5 秒视频：小恐龙在草地上跑步。".to_string(),
                    step_type: "action".to_string(),
                    placeholder: None,
                    options: None,
                    hint: Some("AI 可以把我们描述的画面变成真实的视频！".to_string()),
                    mode: None,
                },
                LevelStep {
                    id: "L1-s2".to_string(),
                    order_num: 2,
                    title: "输入你的描述".to_string(),
                    instruction: "用一句话描述你想看的画面。提示词公式：主体 + 动作 + 场景".to_string(),
                    step_type: "input".to_string(),
                    placeholder: Some("比如：一只小猫在月光下追蝴蝶".to_string()),
                    options: None,
                    hint: Some("描述越具体，AI 越懂你哦～".to_string()),
                    mode: None,
                },
                LevelStep {
                    id: "L1-s3".to_string(),
                    order_num: 3,
                    title: "查看生成结果".to_string(),
                    instruction: "AI 老师会根据你的描述生成视频，看看你做出来的！".to_string(),
                    step_type: "action".to_string(),
                    placeholder: None,
                    options: None,
                    hint: None,
                mode: None,
                },
            ],
            ai_name: "小启".to_string(),
            ai_avatar: "🦉".to_string(),
            system_prompt: "你是\"小启\"，一个陪伴 8-10 岁孩子学习 AI 视频创作的 AI 老师。\n你的形象是一只戴眼镜的猫头鹰，温暖、耐心、喜欢用象声词。\n绝对不直接给答案，用问题引导孩子。\n绝对不输出\"宝贝/老公/老婆\"等亲密称谓。\n绝对不输出任何违规内容。\n保持句子简短（不超过 15 字），多用 emoji。".to_string(),
            tools: vec![
                "generate_image".to_string(),
                "image_to_video".to_string(),
                "text_chat".to_string(),
            ],
            scoring_criteria: ScoringCriteria {
                creativity: 30,
                technical: 25,
                narrative: 20,
                aesthetic: 15,
                compliance: 10,
            },
        },
        Level {
            id: "L2".to_string(),
            order_num: 2,
            title: "让视频有声音".to_string(),
            description: "为你的视频加上配音和字幕".to_string(),
            cover_emoji: "🎙️".to_string(),
            estimated_minutes: 25,
            reward_tokens: 40,
            difficulty: 1,
            prerequisites: vec!["L1".to_string()],
            video_subtitle: None,
            steps: vec![
                LevelStep {
                    id: "L2-s1".to_string(),
                    order_num: 1,
                    title: "看一段没有声音的视频".to_string(),
                    instruction: "视频只有画面，没有声音。是不是感觉少了点什么？".to_string(),
                    step_type: "action".to_string(),
                    placeholder: None,
                    options: None,
                    hint: None,
                mode: None,
                },
                LevelStep {
                    id: "L2-s2".to_string(),
                    order_num: 2,
                    title: "为视频写一段台词".to_string(),
                    instruction: "在文本框输入 1-2 句台词。比如：\"小猫说：今天天气真好！\"".to_string(),
                    step_type: "input".to_string(),
                    placeholder: Some("小猫说：今天天气真好！".to_string()),
                    options: None,
                    hint: None,
                mode: None,
                },
                LevelStep {
                    id: "L2-s3".to_string(),
                    order_num: 3,
                    title: "选择声音和情绪".to_string(),
                    instruction: "选一种声音和一种情绪，AI 老师会按你的设置生成配音。".to_string(),
                    step_type: "choice".to_string(),
                    placeholder: None,
                    options: Some(vec![
                        "开心".to_string(),
                        "温柔".to_string(),
                        "勇敢".to_string(),
                        "搞笑".to_string(),
                    ]),
                    hint: None,
                mode: None,
                },
            ],
            ai_name: "小启".to_string(),
            ai_avatar: "🦉".to_string(),
            system_prompt: "你是\"小启\"，一个陪伴 8-10 岁孩子学习 AI 视频创作的 AI 老师。\n当前任务：教孩子理解视频+音频=完整作品，体验 TTS 配音。\n引导孩子选择合适的声音和情绪。".to_string(),
            tools: vec![
                "synthesize_speech".to_string(),
                "add_subtitle".to_string(),
            ],
            scoring_criteria: ScoringCriteria {
                creativity: 30,
                technical: 25,
                narrative: 20,
                aesthetic: 15,
                compliance: 10,
            },
        },
        Level {
            id: "L3".to_string(),
            order_num: 3,
            title: "让角色\"动\"起来".to_string(),
            description: "学习 5 要素，写出更具体的描述".to_string(),
            cover_emoji: "✨".to_string(),
            estimated_minutes: 25,
            reward_tokens: 40,
            difficulty: 1,
            prerequisites: vec!["L2".to_string()],
            video_subtitle: None,
            steps: vec![
                LevelStep {
                    id: "L3-s1".to_string(),
                    order_num: 1,
                    title: "对比两个提示词".to_string(),
                    instruction: "对比\"一只狗\"和\"白色小柴犬戴红色围巾在雪地打雪仗\"生成的视频。哪个更好？".to_string(),
                    step_type: "action".to_string(),
                    placeholder: None,
                    options: None,
                    hint: None,
                mode: None,
                },
                LevelStep {
                    id: "L3-s2".to_string(),
                    order_num: 2,
                    title: "用 5 要素写描述".to_string(),
                    instruction: "5 要素 = 颜色 + 品种/类型 + 装饰 + 场景 + 动作".to_string(),
                    step_type: "input".to_string(),
                    placeholder: Some("比如：一只橙色的小猫戴着蝴蝶结在花园里追蜻蜓".to_string()),
                    options: None,
                    hint: Some("5 要素齐全 = 满分！".to_string()),
                    mode: None,
                },
            ],
            ai_name: "小启".to_string(),
            ai_avatar: "🦉".to_string(),
            system_prompt: "你是\"小启\"，一个陪伴 8-10 岁孩子学习 AI 视频创作的 AI 老师。\n当前任务：教\"提示词工程\"基础——描述越具体，结果越好。\n教孩子用\"5 要素\"（颜色+品种+装饰+场景+动作）写描述。".to_string(),
            tools: vec![
                "generate_image".to_string(),
                "image_to_video".to_string(),
                "text_chat".to_string(),
            ],
            scoring_criteria: ScoringCriteria {
                creativity: 30,
                technical: 25,
                narrative: 20,
                aesthetic: 15,
                compliance: 10,
            },
        },
        Level {
            id: "L4".to_string(),
            order_num: 4,
            title: "5 秒分镜练习".to_string(),
            description: "用 3 个镜头讲一段 15 秒的小故事".to_string(),
            cover_emoji: "🎞️".to_string(),
            estimated_minutes: 30,
            reward_tokens: 50,
            difficulty: 2,
            prerequisites: vec!["L3".to_string()],
            video_subtitle: None,
            steps: vec![
                LevelStep {
                    id: "L4-s1".to_string(),
                    order_num: 1,
                    title: "了解分镜".to_string(),
                    instruction: "一段 15 秒视频 = 3 个镜头 × 5 秒。镜头：远景 / 中景 / 特写。".to_string(),
                    step_type: "action".to_string(),
                    placeholder: None,
                    options: None,
                    hint: None,
                mode: None,
                },
                LevelStep {
                    id: "L4-s2".to_string(),
                    order_num: 2,
                    title: "写 3 个镜头的描述".to_string(),
                    instruction: "主题自选。每个镜头要有清楚的开始、过程、结束。".to_string(),
                    step_type: "input".to_string(),
                    placeholder: Some("镜头1：...\n镜头2：...\n镜头3：...".to_string()),
                    options: None,
                    hint: None,
                mode: None,
                },
            ],
            ai_name: "创创".to_string(),
            ai_avatar: "🎬".to_string(),
            system_prompt: "你是\"创创\"，一个陪伴 11-13 岁孩子学习 AI 创作的 AI 导师。\n当前任务：教\"分镜\"概念，导演思维。\n孩子需要写 3 个镜头的描述，引导他们用\"开始→过程→结果\"的逻辑。".to_string(),
            tools: vec![
                "generate_image".to_string(),
                "image_to_video".to_string(),
                "add_bgm".to_string(),
            ],
            scoring_criteria: ScoringCriteria {
                creativity: 30,
                technical: 25,
                narrative: 25,
                aesthetic: 10,
                compliance: 10,
            },
        },
        Level {
            id: "L5".to_string(),
            order_num: 5,
            title: "色彩与情绪".to_string(),
            description: "理解色彩如何传递情绪".to_string(),
            cover_emoji: "🎨".to_string(),
            estimated_minutes: 30,
            reward_tokens: 50,
            difficulty: 2,
            prerequisites: vec!["L4".to_string()],
            video_subtitle: None,
            steps: vec![
                LevelStep {
                    id: "L5-s1".to_string(),
                    order_num: 1,
                    title: "看色彩对比".to_string(),
                    instruction: "看 6 张\"森林\"图。同一场景不同色彩，情绪完全不同。".to_string(),
                    step_type: "action".to_string(),
                    placeholder: None,
                    options: None,
                    hint: None,
                mode: None,
                },
                LevelStep {
                    id: "L5-s2".to_string(),
                    order_num: 2,
                    title: "用色彩词描述画面".to_string(),
                    instruction: "选择一个你想表达的情绪（神秘/温馨/紧张/欢乐），用色彩词描述一个场景。".to_string(),
                    step_type: "input".to_string(),
                    placeholder: Some("比如：寒冷的蓝色雪夜森林，神秘而安静".to_string()),
                    options: None,
                    hint: None,
                mode: None,
                },
            ],
            ai_name: "创创".to_string(),
            ai_avatar: "🎬".to_string(),
            system_prompt: "你是\"创创\"，一个陪伴 11-13 岁孩子学习 AI 创作的 AI 导师。\n当前任务：教\"色彩\"如何传递情绪。\n教孩子识别冷色/暖色/低饱和/高饱和的不同情感。".to_string(),
            tools: vec!["generate_image".to_string()],
            scoring_criteria: ScoringCriteria {
                creativity: 30,
                technical: 25,
                narrative: 20,
                aesthetic: 15,
                compliance: 10,
            },
        },
        // ---------- W3.7+ 拉片复刻类关卡 ----------
        Level {
            id: "L6".to_string(),
            order_num: 6,
            title: "🎞️ 拉一帧复刻".to_string(),
            description: "上传一段视频，选一个最心动的镜头，用你的角色+风格复刻出来".to_string(),
            cover_emoji: "🎞️".to_string(),
            estimated_minutes: 8,
            reward_tokens: 25,
            difficulty: 3,
            prerequisites: vec!["L5".to_string()],
            video_subtitle: None,
            steps: vec![
                LevelStep {
                    id: "L6-s1".to_string(),
                    order_num: 1,
                    title: "上传参考视频".to_string(),
                    instruction: "上传一段本地 mp4 / webm 视频（≤120s, ≤100MB）。".to_string(),
                    step_type: "reference_setup".to_string(),
                    placeholder: None,
                    options: None,
                    hint: Some("选一段你印象深刻的镜头".to_string()),
                    mode: None,
                },
                LevelStep {
                    id: "L6-s2".to_string(),
                    order_num: 2,
                    title: "选 1 帧复刻".to_string(),
                    instruction: "从抽出的 5 帧里挑你最心动的 1 帧,选定你的角色+风格,点击「复刻这一帧」。".to_string(),
                    step_type: "reference_recreate".to_string(),
                    placeholder: None,
                    options: None,
                    hint: Some("保持原始构图,迁移风格".to_string()),
                    mode: Some("single".to_string()),
                },
            ],
            ai_name: "创创".to_string(),
            ai_avatar: "🎬".to_string(),
            system_prompt: "你是\"创创\"🎬,一位会拉片的分镜师。\n当前任务:孩子会上传一段参考视频,系统会从中抽出 5 帧,孩子选其中一帧让你按其角色+风格复刻。\n\n工作要点:\n- 用户消息末尾的 [Reference context] 段里有 source_image_url(被选中的那一帧)和 user_intent\n- 用 [Reference context] 段里的 source_image_url 当参考构图\n- 必须保留原始构图、主体动作、镜头景别\n- 把风格迁移到用户当前选定的角色+风格上\n- 输出时简短描述 1-2 句「复刻的要点」,再调用 generate_image 工具生成".to_string(),
            tools: vec!["generate_image".to_string()],
            scoring_criteria: ScoringCriteria {
                creativity: 30,
                technical: 30,
                narrative: 10,
                aesthetic: 20,
                compliance: 10,
            },
        },
        Level {
            id: "L7".to_string(),
            order_num: 7,
            title: "📽️ 整段分镜复刻".to_string(),
            description: "把一段视频里的 N 帧用同一个角色+风格统一复刻,做出属于你的故事板".to_string(),
            cover_emoji: "📽️".to_string(),
            estimated_minutes: 15,
            reward_tokens: 40,
            difficulty: 4,
            prerequisites: vec!["L6".to_string()],
            video_subtitle: None,
            steps: vec![
                LevelStep {
                    id: "L7-s1".to_string(),
                    order_num: 1,
                    title: "上传参考视频".to_string(),
                    instruction: "上传一段本地 mp4 / webm 视频(≤120s, ≤100MB)。".to_string(),
                    step_type: "reference_setup".to_string(),
                    placeholder: None,
                    options: None,
                    hint: Some("一段有起承转合的视频效果更好".to_string()),
                    mode: None,
                },
                LevelStep {
                    id: "L7-s2".to_string(),
                    order_num: 2,
                    title: "整段复刻".to_string(),
                    instruction: "系统会从视频抽 N 帧,按用户选定的角色+风格一次性复刻全部帧,输出一致的故事板。".to_string(),
                    step_type: "reference_recreate".to_string(),
                    placeholder: None,
                    options: None,
                    hint: Some("确保所有帧的视觉一致 — 同一个世界".to_string()),
                    mode: Some("batch".to_string()),
                },
            ],
            ai_name: "创创".to_string(),
            ai_avatar: "🎬".to_string(),
            system_prompt: "你是\"创创\"🎬,一位会拉片的分镜师。\n当前任务:孩子会一次性要求你复刻视频里的全部 N 帧,产生一致的故事板。\n\n工作要点:\n- 用户会按顺序多次调你,每次消息末尾的 [Reference context] 段里有 source_image_url + timestamp\n- 务必保证 N 张图视觉一致 — 用同一个角色、同一种色彩基调、同一种笔触\n- 在第一张之前先简单描述\"故事板主题\",然后开始生图\n- 后续每张都要呼应\"保持上一张的角色+风格\"\n- 整体应像同一个世界里的连续镜头".to_string(),
            tools: vec!["generate_image".to_string()],
            scoring_criteria: ScoringCriteria {
                creativity: 25,
                technical: 25,
                narrative: 20,
                aesthetic: 20,
                compliance: 10,
            },
        },
    ]
}
